services:
  backend:
    build:
      context: ./backend
    container_name: litmt-backend
    env_file:
      - ./backend/.env
    environment:
      - CORS_ALLOW_ORIGINS=http://localhost:3000,http://localhost:3001
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  frontend:
    build:
      context: ./litmt
    container_name: litmt-frontend
    env_file:
      - ./litmt/.env.local
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    ports:
      - "3001:3000"
    volumes:
      - ./litmt:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run dev -- -H 0.0.0.0"

